/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/screens/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
  ],
  plugins: [],
  theme: {
    container: {
      center: true,
      padding: '2rem',
    },
    fontSize: {
      xs1: ['10px', {lineHeight: '16px', letterSpacing: '0'}],
      xs: ['12px', {lineHeight: '18px', letterSpacing: '0'}],
      sm: ['14px', {lineHeight: '20px', letterSpacing: '0'}],
      lg: ['16px', {lineHeight: '24px', letterSpacing: '0'}],
      xl: ['18px', {lineHeight: '26px', letterSpacing: '0'}],
      '2xl': ['20px', {lineHeight: '30px', letterSpacing: '0'}],
      '3xl': ['24px', {lineHeight: '36px', letterSpacing: '0'}],
      '4xl': ['32px', {lineHeight: '40px', letterSpacing: '0'}],
      '5xl': ['40px', {lineHeight: '48px', letterSpacing: '0'}],
      '6xl': ['48px', {lineHeight: '56px', letterSpacing: '0'}],
      '7xl': ['56px', {lineHeight: '64px', letterSpacing: '-0.02'}],
      'custom-title': ['24px', {lineHeight: '32px', letterSpacing: '0'}],
      'custom-lyrics': ['18px', {lineHeight: '26px', letterSpacing: '0'}],
    },
    extend: {
      truncate: {
        lines: {
          2: '2',
          3: '3',
        },
      },
      fontFamily: {
        'nokia-bold': [
          'Nokia Pure Headline Bold',
          'NokiaPureHeadline-Bold',
          'NokiaPureHeadline_Bold',
          'NOKIAPUREHEADLINE_BOLD',
          'Arial',
          'sans-serif',
        ],
        'nokia-extraBold': [
          'NokiaPureHeadline_XBd',
          'NokiaPureHeadline-ExtraBold',
          'NokiaPureHeadline_XBd..',
          'NOKIAPUREHEADLINE_XBD',
          'Arial',
          'sans-serif',
        ],
        'nokia-regular': [
          'Nokia Pure Headline Regular',
          'NokiaPureHeadline-Regular',
          'NOKIAPUREHEADLINE_RG',
          'NOKIAPUREHEADLINE_RG.TTF',
          'Arial',
          'sans-serif',
        ],
        'nokia-light': [
          'Nokia Pure Headline Light',
          'NokiaPureHeadline-Light',
          'NokiaPureHeadline_Lt',
          'NOKIAPUREHEADLINE_LT',
          'Arial',
          'sans-serif',
        ],
        'nokia-ultraLight': [
          'Nokia Pure Headline Ultra Light',
          'NokiaPureHeadline-UltraLight',
          'NOKIAPUREHEADLINE_ULTRALIGHT',
          'Arial',
          'sans-serif',
        ],
        'Lato-Light': ['Lato-Light', 'Lato Light', 'Arial', 'sans-serif'],
        'Lato-Regular': ['Lato-Regular', 'Lato', 'Arial', 'sans-serif'],
        'Lato-Black': ['Lato-Black', 'Lato Black', 'Arial', 'sans-serif'],
        'Lato-Bold': ['Lato-Bold', 'Lato Bold', 'Arial', 'sans-serif'],
        'Lato-Thin': ['Lato-Thin', 'Lato Thin', 'Arial', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        sans: [
          'Nokia Pure Headline Regular',
          'NokiaPureHeadline-Regular',
          'NOKIAPUREHEADLINE_RG',
          'Arial',
          'sans-serif',
        ],
      },
      colors: {
        'primary-1': '#FDFDFD',
        'primary-2': '#FBFBFB',
        'primary-3': '#F8F8F8',
        'primary-4': '#F4F4F4',
        'primary-5': '#F1F1F1',
        'primary-6': '#EEEEEE',
        'primary-7': '#CACACA',
        'primary-8': '#A9A9A9',
        'primary-9': '#888888',
        'primary-10': '#6B6B6B',
        'secondary-1': '#EBEDEE',
        'secondary-2': '#D0D3D5',
        'secondary-3': '#AAB0B4',
        'secondary-4': '#838B91',
        'secondary-5': '#5D6870',
        'secondary-6': '#3A4750',
        'secondary-7': '#313C44',
        'secondary-8': '#293239',
        'secondary-9': '#21282E',
        'secondary-10': '#1A2024',
        'accent-1': '#FDF4E8',
        'accent-2': '#FAE5C7',
        'accent-3': '#F6D09A',
        'accent-4': '#F2BA6C',
        'accent-5': '#EEA63F',
        'accent-6': '#EA9215',
        'accent-7': '#C77C12',
        'accent-8': '#A6680F',
        'accent-9': '#85530C',
        'accent-10': '#694209',
        'accent-11': '#593807',
        dark: {
          'secondary-1': '#FDFDFD',
          'secondary-2': '#FBFBFB',
          'secondary-3': '#F8F8F8',
          'secondary-4': '#F4F4F4',
          'secondary-5': '#F1F1F1',
          'secondary-6': '#EEEEEE',
          'secondary-7': '#CACACA',
          'secondary-8': '#A9A9A9',
          'secondary-9': '#888888',
          'secondary-10': '#6B6B6B',
          'primary-1': '#EBEDEE',
          'primary-2': '#D0D3D5',
          'primary-3': '#AAB0B4',
          'primary-4': '#838B91',
          'primary-5': '#5D6870',
          'primary-6': '#3A4750',
          'primary-7': '#313C44',
          'primary-8': '#293239',
          'primary-9': '#21282E',
          'primary-10': '#1A2024',
          'accent-1': '#FDF4E8',
          'accent-2': '#FAE5C7',
          'accent-3': '#F6D09A',
          'accent-4': '#F2BA6C',
          'accent-5': '#EEA63F',
          'accent-6': '#EA9215',
          'accent-7': '#C77C12',
          'accent-8': '#A6680F',
          'accent-9': '#85530C',
          'accent-10': '#694209',
          'accent-11': '#593807',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {height: 0},
          to: {height: 'var(--radix-accordion-content-height)'},
        },
        'accordion-up': {
          from: {height: 'var(--radix-accordion-content-height)'},
          to: {height: 0},
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
};
